---
- name: "Multiple commands on IOS device"
  hosts: IOS
  connection: local
  tasks:
  - ios_command:
      commands: 
       - show version
       - show ip route
      host: "{{inventory_hostname}}"
      username: cisco
      password: cisco